services:
  backend:
    depends_on:
      - backend-db
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - BIND_ADDRESS=0.0.0.0
      - DATABASE_URL=postgres://postgres:postgres@backend-db:5432/paymaster
      - RUN_SEED=true
    env_file:
      - apps/backend/.env
    networks:
      app-network:

  backend-db:
    image: postgres:17.6-alpine@sha256:52c2130c698a7fe22ac565c35a3b8c4d05af65addb994416b84d1bcf0b900dcd
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=paymaster
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      app-network:

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        - BUILD_MODE=development
    ports:
      - '3001:80'
    depends_on:
      - backend
    env_file:
      - apps/frontend/.env
    networks:
      app-network:

networks:
  app-network:

volumes:
  postgres-data:
